services:
  wallet-api:
    read_only: true
    init: true
    environment:
      BIND_ADDR: "0.0.0.0:8080"
      CERT_NAME: ntls-api
    devices:
      - /dev/sgx/enclave
      - /dev/sgx/provision
    expose:
      - "8080"

  asset-services-redis:
    image: "redis:6-alpine"
    expose:
      - "6379"
    # Enable persistence
    command: "redis-server --save 60 1"

  asset-services-api:
    read_only: true
    init: true
    environment:
      BIND_ADDR: "0.0.0.0:8081"
      RUST_LOG: "info"
      # TODO(Pi): CERT_NAME: ntls-services
      CERT_NAME: ntls-api
    expose:
      - "8081"

  asset-services-worker:
    read_only: true
    init: true
    environment:
      PREFLIGHT_CHECK_LEVEL: remote

      ONFIDO_API_TOKEN:
      TWILIO_ACCOUNT_SID:
      TWILIO_AUTH_TOKEN:
      TWILIO_VERIFY_SERVICE_SID:
      TWILIO_MESSAGING_SERVICE_SID:
