# Nautilus Wallet demo and staging deployment

networks:
  wallet-demo:
  wallet-staging:

services:
  # Docs: https://github.com/nginx-proxy/nginx-proxy
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    networks:
      - wallet-demo
      - wallet-staging
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/tls:/etc/nginx/certs:ro

  wallet-demo-api:
    extends:
      file: common-services.yaml
      service: wallet-api
    image: ghcr.io/ntls-io/sgx-wallet-hw:demo
    environment:
      VIRTUAL_HOST: ntls-api.registree.io,wallet-demo-api.ntls.io
    devices:
      - /dev/sgx/enclave
      - /dev/sgx/provision
    networks:
      - wallet-demo
    volumes:
      - wallet-store-demo:/app/wallet_store

  wallet-staging-api:
    extends:
      file: common-services.yaml
      service: wallet-api
    image: ghcr.io/ntls-io/sgx-wallet-hw:main
    environment:
      VIRTUAL_HOST: wallet-staging-api.ntls.io
    networks:
      - wallet-staging
    volumes:
      - wallet-store-staging:/app/wallet_store

  asset-services-demo-redis:
    extends:
      file: common-services.yaml
      service: assset-services-redis
    networks:
      - wallet-demo
    volumes:
      - asset-services-demo-redis-data:/data

  asset-services-staging-redis:
    extends:
      file: common-services.yaml
      service: assset-services-redis
    networks:
      - wallet-staging
    volumes:
      - asset-services-staging-redis-data:/data

  asset-services-demo-api:
    extends:
      file: common-services.yaml
      service: assset-services-api
    depends_on:
      - asset-services-demo-redis
    image: ghcr.io/ntls-io/asset-services-api:demo
    environment:
      BROKER_URL: "redis://asset-services-demo-redis:6379"
      # For nginx-proxy:
      VIRTUAL_HOST: ntls-services.registree.io,wallet-demo-services.ntls.io
    networks:
      - wallet-demo

  asset-services-demo-worker:
    extends:
      file: common-services.yaml
      service: assset-services-worker
    depends_on:
      - asset-services-demo-redis
    image: ghcr.io/ntls-io/asset-services-worker:demo
    environment:
      BROKER_URL: "redis://asset-services-demo-redis:6379"
    networks:
      - wallet-demo

  asset-services-staging-api:
    extends:
      file: common-services.yaml
      service: assset-services-api
    depends_on:
      - asset-services-staging-redis
    image: ghcr.io/ntls-io/asset-services-api:main
    environment:
      BROKER_URL: "redis://asset-services-staging-redis:6379"
      # For nginx-proxy:
      VIRTUAL_HOST: wallet-staging-services.ntls.io
      # TODO(Pi): CERT_NAME: ntls-services
      CERT_NAME: ntls-api
    networks:
      - wallet-staging

  asset-services-staging-worker:
    extends:
      file: common-services.yaml
      service: assset-services-worker
    depends_on:
      - asset-services-staging-redis
    image: ghcr.io/ntls-io/asset-services-worker:main
    environment:
      BROKER_URL: "redis://asset-services-staging-redis:6379"
    networks:
      - wallet-staging

volumes:
  wallet-store-demo:
  wallet-store-staging:
  asset-services-demo-redis-data:
  asset-services-staging-redis-data:
