networks:
  wallet-bhutan-demo:

services:
  nginx-proxy:
    networks:
      - wallet-bhutan-demo

  wallet-bhutan-demo-api:
    extends:
      file: common-services.yaml
      service: wallet-api
    image: ghcr.io/ntls-io/sgx-wallet-hw:bhutan-demo
    environment:
      VIRTUAL_HOST: wallet-bhutan-api.ntls.io
    networks:
      - wallet-bhutan-demo
    volumes:
      - wallet-store-bhutan-demo:/app/wallet_store

  asset-services-bhutan-demo-redis:
    extends:
      file: common-services.yaml
      service: assset-services-redis
    networks:
      - wallet-bhutan-demo
    volumes:
      - asset-services-bhutan-demo-redis-data:/data

  asset-services-bhutan-demo-api:
    extends:
      file: common-services.yaml
      service: assset-services-api
    depends_on:
      - asset-services-bhutan-demo-redis
    image: ghcr.io/ntls-io/asset-services-api:bhutan-demo
    environment:
      BROKER_URL: "redis://asset-services-bhutan-demo-redis:6379"
      # For nginx-proxy:
      VIRTUAL_HOST: wallet-bhutan-services.ntls.io
    expose:
      - "8081"
    networks:
      - wallet-bhutan-demo

  asset-services-bhutan-demo-worker:
    extends:
      file: common-services.yaml
      service: assset-services-worker
    depends_on:
      - asset-services-bhutan-demo-redis
    image: ghcr.io/ntls-io/asset-services-worker:bhutan-demo
    environment:
      BROKER_URL: "redis://asset-services-bhutan-demo-redis:6379"
    networks:
      - wallet-bhutan-demo

volumes:
  wallet-store-bhutan-demo:
  asset-services-bhutan-demo-redis-data:
