# Add an instance for the XRP hackathon demo.

services:

  wallet-api-xrp:
    image: ghcr.io/registreerocks/sgx-wallet-hw:xrp-demo
    read_only: true
    init: true
    environment:
      BIND_ADDR: "0.0.0.0:8080"
      VIRTUAL_HOST: xrpl-api.registree.io
      # TODO:
      CERT_NAME: ntls-api
    devices:
      - /dev/sgx/enclave
      - /dev/sgx/provision
    volumes:
      - wallet-store-xrp:/app/wallet_store
    expose:
      - "8080"

volumes:
  wallet-store-xrp:
