# Nautilus Wallet demo deployment

services:
  # Docs: https://github.com/nginx-proxy/nginx-proxy
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/tls:/etc/nginx/certs:ro

  wallet-api-demo:
    image: ghcr.io/registreerocks/sgx-wallet-hw:main
    read_only: true
    init: true
    environment:
      BIND_ADDR: "0.0.0.0:8080"
      VIRTUAL_HOST: ntls-api.registree.io
      CERT_NAME: ntls-api
    devices:
      - /dev/sgx/enclave
      - /dev/sgx/provision
    volumes:
      - wallet-store-demo:/app/wallet_store
    expose:
      - "8080"

  asset-services-redis:
    image: "redis:6-alpine"
    expose:
      - "6379"
    # Enable persistence
    command: "redis-server --save 60 1"
    volumes:
      - asset-services-redis-data:/data

  asset-services-api:
    depends_on:
      - asset-services-redis
    image: ghcr.io/registreerocks/asset-services-api:xrp-demo
    read_only: true
    init: true
    environment:
      BROKER_URL: "redis://asset-services-redis:6379"
      BIND_ADDR: "0.0.0.0:8081"
      RUST_LOG: "info"
      # For nginx-proxy:
      VIRTUAL_HOST: ntls-services.registree.io
      # TODO(Pi): CERT_NAME: ntls-services
      CERT_NAME: ntls-api
    expose:
      - "8081"

  asset-services-worker:
    depends_on:
      - asset-services-redis
    image: ghcr.io/registreerocks/asset-services-worker:xrp-demo
    read_only: true
    init: true
    environment:
      BROKER_URL: "redis://asset-services-redis:6379"
      PREFLIGHT_CHECK_LEVEL: remote

      ONFIDO_API_TOKEN:
      TWILIO_ACCOUNT_SID:
      TWILIO_AUTH_TOKEN:
      TWILIO_VERIFY_SERVICE_SID:


volumes:
  wallet-store-demo:
  asset-services-redis-data:
