name: Deploy

on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        type: environment
        required: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: ${{ github.event.inputs.environment }}
    steps:
      # https://github.com/shimataro/ssh-key-action#readme
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      # https://github.com/actions/checkout#readme
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy (docker compose)
        env:
          # Tell docker compose where to connect to:
          DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
          # https://docs.docker.com/compose/reference/envvars/#compose_file
          COMPOSE_FILE: ${{ secrets.COMPOSE_FILE }}

          # Configuration consumed by docker compose:
          ONFIDO_API_TOKEN: ${{ secrets.ONFIDO_API_TOKEN }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_MESSAGING_SERVICE_SID: ${{ secrets.TWILIO_MESSAGING_SERVICE_SID }}
          TWILIO_VERIFY_SERVICE_SID: ${{ secrets.TWILIO_VERIFY_SERVICE_SID }}
        run: |
          docker compose pull
          docker compose up --wait --force-recreate
          docker compose logs
